version: "3.8"

services:
  samanta-campaigns-backend:
    build:
      context: .
    container_name: samanta-campaigns-backend
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8001
    ports:
      - 8001:8001
    expose:
      - "8001"
    volumes:
      - .:/usr/src/app
    networks:
      - webnet

  samanta-campaigns-backend2:
    build:
      context: .
    container_name: samanta-campaigns-backend2
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/app
    networks:
      - webnet
  script-link-task:
    build:
      context: .
    container_name: script-link-task
    restart: always
    command: python3 scrape_links_task.py
    volumes:
      - .:/usr/src/app
    networks:
      - webnet

  run-due-task:
    build:
      context: .
    container_name: run-due-task
    restart: always
    command: python3 run_due_campaigns_task.py
    volumes:
      - .:/usr/src/app
    networks:
      - webnet

  deactivate-active-task:
    build:
      context: .
    container_name: deactivate-active-task
    restart: always
    command: python3 deactivate_expired_campaigns_task.py
    volumes:
      - .:/usr/src/app
    networks:
      - webnet

networks:
  webnet:
    external: true
    name: webnet
