version: "3.8"

services:
  django:
    image: python:3.9
    container_name: django
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/myproject
    networks:
      - webnet

networks:
  webnet:
    external: true
