version: "3.8"

services:
  samanta-campaigns-backend:
    build: 
      context: .
    container_name: samanta-campaigns-backend
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8001

    ports:
      - 8001:8001
    expose:
      - "8001"
    volumes:
      - .:/usr/src/app
    networks:
      - default

networks:
    default:
        name: webnet